### ISSUE TITLE
Task: create a new boilerplate for Astro

### ISSUE THREAD

**Issue by devmozao** [eruptionjs/core#24]
Since my next project is going on with Astro, I want to create a standard approach to work with Astro, but in a way that is oppionionated with React and MDX, while also bringing the core Eruption features to it.

**Comment by devMozao** [comment]
Found several problems related with Astro 2.0 config related with prettier/eslint. Needs further investigation and new testing. Apparently, it was related with the astro vscode plugin conflicting with prettier's config. /sad

**Comment by devmozao** [comment]
Astro ATM is out of scope. Will resume this when things makes sense again to support it.
