### ISSUE TITLE
Task: buy a domain for EruptionJS

### ISSUE THREAD

**Issue by devMozao** [eruptionjs/core#25]
Self explanatory. As I discussed with @raisiqueira, Eruption will adopt a domain that will link to the official docs of the project (docs that will be done later on).

We discussed the possibility of using the .dev, .com and .org as the top level domain (TLD), but no commits were made on the matter.

Donations are welcome to help buy the domain.

**Comment by raisiqueira** [comment]
My vote is to buy a `.dev` domain 💯

**Comment by luigieai** [comment]
Solved by @raisiqueira :)
