### ISSUE TITLE
Add CI pipeline

### ISSUE THREAD

**Issue by luigieai** [eruptionjs/core#26]
In a production point of view, I think that we can improve DX providing default pipelines for the boilerplate, my initial idea is providing github actions workflows that test and build the app, and in near future with the project's CLI done, maybe we can add base pipelines for another products like GitlabCI, Jenkins and etc.... 

If this issue fits the project purpose and roadmap, I'm open to discuss more about the feature and help to implement it.

**Comment by devMozao** [comment]
Let's discuss this further, 'cuz I don't have any experience with GH CI's proccess. (And since we're improving to have a CLI and also an official docs, having a CI will help a lot So any help on the matter, it's appretiated.)

**Comment by luigieai** [comment]
Surely, idk what exactly we can start discussing, but I can start creating a prototype about this feature and we can start from there

**Comment by luigieai** [comment]
Currently helping our CLI to go production before we can work about this question on Core 😃

**Comment by raisiqueira** [comment]
closed by #34
