### ISSUE TITLE
implement qr-code on dev server

### ISSUE THREAD

**Issue by devmozao** [eruptionjs/core#48]
from release v1.7: implement qr-code to open application on mobile and facilitate dev testing for responsives

**Comment by raisiqueira** [comment]
I've tested the `vite-plugin-qrcode` and it looks working well. The output was two QR Code due Docker was running, not a concern here.

![CleanShot 2023-12-09 at 15 58 02](https://github.com/eruptionjs/core/assets/2914170/b8539986-7b42-4c0e-97fe-a5d5d3f203d3)
