### ISSUE TITLE
add commitlint-cli prompt to the project

### ISSUE THREAD

**Issue by devMozao** [eruptionjs/core#5]

**Comment by SalahAdDin** [comment]
You already did it, isn't it?

**Comment by devMozao** [comment]
> You already did it, isn't it?

I tried with `@commitlint/cz-commitlint` but wasn't happy with it because cz-commitlint have its dependencies with high vulnerability issues, with is not desired to the boilerplate. the commitlint default is configured.

The task is to revisit this topic and look for alternatives to prompt commit.

**Comment by SalahAdDin** [comment]
> > You already did it, isn't it?
> 
> I tried with `@commitlint/cz-commitlint` but wasn't happy with it because cz-commitlint has its dependencies with high vulnerability issues, with is not desired in the boilerplate. the commitlint default is configured.
> 
> The task is to revisit this topic and look for alternatives to prompt commit.

Is it for changelog?

**Comment by devMozao** [comment]
done at commit 106280699ca07a0d1c74d3d260c7d819c4f4425b

**Comment by SalahAdDin** [comment]
This does help to write commits with the CLI, right?

**Comment by devMozao** [comment]
> This does help to write commits with the CLI, right?

correct! you can use `npm run commit` and the CLI will guide you how to commit in the project, following the config that was made on `[commitlint.config.ts](https://github.com/eruptionjs/core/blob/main/commitlint.config.ts)`
